<a href="https://colab.research.google.com/github/GJunakovic/Projekt-Quiz/blob/main/Vjezba01DR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#zad 1

import numpy as np

matrica1 = np.random.randint(1,7, size=(2,3))
matrica2 = np.random.randint(1,7, size=(2,3))

print(matrica1)
print('-------')
print(matrica2)


vektor1 = matrica1.reshape(6)
vektor2 = matrica2.reshape(6)

scalar_product = np.dot(vektor1, vektor2)

print('Skalarni produkt sva vektora = ' , scalar_product)



[[4 1 4]
 [6 5 2]]
-------
[[5 5 2]
 [2 6 5]]
Skalarni produkt sva vektora =  85


In [23]:
# zad 2

def multiply(a,b,c,d):
  matrica1 = np.random.randint(1,7, size=(a,b))
  matrica2 = np.random.randint(1,7, size=(c,d))

  print('Matrica 1 --> ', matrica1)
  print('Matrica 2 -->', matrica2)

  if b != c:
    print('Umnožak matrica nije moguć')
    return None

  umnozak = np.dot(matrica1, matrica2)
  return print('Umnozak matrica --> ', umnozak)

multiply(2,2,2,5)


Matrica 1 -->  [[6 5]
 [5 6]]
Matrica 2 --> [[5 1 6]
 [6 5 1]]
Umnozak matrica -->  [[60 31 41]
 [61 35 36]]


In [42]:
#zad3

def randomArray(m,n,d):

  if d == "uniform":
    min_val = float(input("Unesite minimalnu vrijednost: "))
    max_val = float(input("Unesite maksimalnu vrijednost: "))
    return np.random.uniform(min_val, max_val, size=(m, n))
  elif d == "normal":
    mu = float(input("Unesite srednju vrijednost (mu): "))
    sigma = float(input("Unesite standardnu devijaciju (sigma): "))
    return np.random.normal(mu, sigma, size=(m, n))
  elif d == "poisson":
    lam = float(input("Unesite lambda: "))
    return np.random.poisson(lam, size=(m, n))
  else:
    print('Pogresan unos distribucije!')
    return np.random.normal(0, 1, size=(m, n))

m, n = 5, 7
A = randomArray(m, n, "normal")
print(A)

Unesite srednju vrijednost (mu): 1
Unesite standardnu devijaciju (sigma): 3
[[-1.56997251 -1.40192658 -0.02318856 -0.14887664  5.36996884  1.04871672
   8.348442  ]
 [-1.46291555  5.25830808 -4.00784789  4.35736358  5.4510087  -0.55365578
   1.91035288]
 [-0.85655677 -1.11924892 -5.98141977  3.38652571  6.26332901 -1.40922462
  -3.68116066]
 [-1.17917179 -2.06299258  1.61643785  2.74930291  1.55645716  1.11756104
   5.46756777]
 [ 2.00632563  4.21251856  6.57485502  1.24924209 -2.1212655  -4.29426407
   0.29919318]]
